# Generated by Django 3.1.1 on 2020-10-24 11:17

from django.db import migrations


def create_system(apps, schema_editor):
    System = apps.get_model("visualisation", "System")
    system = System()
    system.name = "default_system"
    system.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_system),
    ]


