# Generated by Django 3.1.1 on 2020-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0002_auto_20201024_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parama',
            name='a00',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a01',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a02',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a11',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a12',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a20',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a21',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parama',
            name='a22',
            field=models.FloatField(default=0),
        ),
    ]
