# Generated by Django 3.1.1 on 2020-10-24 11:44

from django.db import migrations

def create_parama(apps, schema_editor):
    ParamA = apps.get_model("visualisation", "ParamA")
    param = ParamA()
    param.a00 = 4
    param.a01 = -2.5
    param.a02 = 0
    param.a10 = 2
    param.a11 = -3
    param.a12 = 0
    param.a20 = 0
    param.a21 = 0
    param.a22 = 0

    System = apps.get_model("visualisation", "System")
    system = System.objects.get(pk=1)
    param.system = system

    param.save()


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0003_auto_20201024_1143'),
        ('visualisation', '0002_auto_20201024_1117'),
    ]

    operations = [
        migrations.RunPython(create_parama),
    ]
