# Generated by Django 3.1.1 on 2020-10-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0005_auto_20201024_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parama',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualisation.system'),
        ),
        migrations.AlterField(
            model_name='paramc',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualisation.system'),
        ),
    ]
