# Generated by Django 3.1.3 on 2020-11-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0009_integrationmaxstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualisation.system')),
            ],
        ),
    ]
