# Generated by Django 3.1.1 on 2020-10-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0004_auto_20201024_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='parama',
            name='a03',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a04',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a14',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a23',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a24',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a30',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a31',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a32',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a33',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a34',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a40',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a41',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a42',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a43',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parama',
            name='a44',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ParamC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c0', models.FloatField(default=0)),
                ('c1', models.FloatField(default=0)),
                ('c2', models.FloatField(default=0)),
                ('c3', models.FloatField(default=0)),
                ('c4', models.FloatField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.system')),
            ],
        ),
    ]
