# Generated by Django 3.1.1 on 2020-10-24 18:37

from django.db import migrations


def create_paramc(apps, schema_editor):
    ParamC = apps.get_model("visualisation", "ParamC")
    param = ParamC()
    param.c0 = 0
    param.c1 = 0
    param.c2 = 0
    param.c3 = 0
    param.c4 = 0

    System = apps.get_model("visualisation", "System")
    system = System.objects.get(name="default_system")
    param.system = system

    param.save()


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0006_auto_20201024_1833'),
    ]

    operations = [
        migrations.RunPython(create_paramc),
    ]
