# Generated by Django 3.1.3 on 2020-11-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0008_initialvalues_timespan_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMaxStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(default=0.1)),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualisation.system')),
            ],
        ),
    ]
